{% set name = "esmlab" %}
{% set version = "2019.3.16" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 9d58c2cb4e3686f884edf60d5da49f2fb53961a4969d203b953dcfc0f2a8bb16
  

build: 
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"
  noarch: python
  number: 0

requirements:

  host:
    - python
    - pip

  run:
    - python
    - xarray
    - cftime
    - dask
    - netcdf4
    - esmpy
    - xesmf

test:
  source_files:
    - tests
  requires:
    - pytest
  imports:
    - esmlab
  commands:
    - pytest -v tests/test_climatology.py
    - pytest -v tests/test_statistics.py
    - pytest -v tests/test_datasets.py
    - pytest -v tests/utils
    
about:
  
  home: https://github.com/NCAR/esmlab
  license: Apache 2.0
  license_file: LICENSE
  summary: |
    Tools for working with earth system multi-model analyses with xarray. 
  dev_url: https://github.com/NCAR/esmlab
  doc_url: https://esmlab.readthedocs.io/en/latest/

extra:
  recipe-maintainers:
    - andersy005
    - kmpaul
    - jukent
    - matt-long
