{% set name = "esmlab" %}
{% set version = "2019.4.27" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 2a9b583e20491ec4509ee32c8230dee80969f6c99837e441073738a235876f72
  

build: 
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"
  noarch: python
  number: 0

requirements:

  host:
    - python >3.5
    - pip
    - setuptools_scm
    - setuptools_scm_git_archive
    

  run:
    - python >3.5
    - xarray
    - cftime
    - dask
    - netcdf4
    - esmpy
    - xesmf

test:
  imports:
    - esmlab
    - esmlab.config
    
about:
  
  home: https://github.com/NCAR/esmlab
  license: Apache 2.0
  license_file: LICENSE
  summary: |
    Tools for working with earth system multi-model analyses with xarray. 
  dev_url: https://github.com/NCAR/esmlab
  doc_url: https://esmlab.readthedocs.io/en/latest/

extra:
  recipe-maintainers:
    - andersy005
    - kmpaul
    - jukent
    - matt-long
 
