{% set name = "esmlab" %}
{% set version = "2019.2.0" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 395d146889e8e3e84cd0f5e1ea989f8b38043dd7f95e08f33edfe1efd8a3b38f
  

build: 
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"
  noarch: python
  number: 0

requirements:

  host:
    - python
    - pip

  run:
    - python
    - xarray
    - cftime
    - dask
    - netcdf4

test:
  source_files:
    - tests
  requires:
    - pytest
  imports:
    - esmlab
  commands:
    - pytest --verbose

about:
  
  home: https://github.com/NCAR/esmlab
  license: Apache 2.0
  license_file: LICENSE
  summary: |
    Tools for working with earth system multi-model analyses with xarray. 
  dev_url: https://github.com/NCAR/esmlab
  doc_url: https://esmlab.readthedocs.io/en/latest/

extra:
  recipe-maintainers:
    - andersy005
    - kmpaul
    - jukent
    - matt-long
