travis:
  secure:
    BINSTAR_TOKEN: gbG20giihWw6daCcJ0cCXjUkezCzu0yYAvBfRropT2hIQxdQgGWx1hCFIcLbgLAzQBNmPgI8nHit1SjvWdsgXV5VsKXNl9HYcdzrBwi89k363cnJ7rFB2Uc6LokoLvLGv136HhHrhNx3TQvlaribs0ODWdvd5F3W44ma8SIp7mDGWU4+JWs0/3GG6+JsnMoTgJz2pb2QIA+xuAb5t8/k6QLWwWY/QPX4tOYvnnnN/A5YCltK1El6GdE3M0FTR9XLK3zBjBbf25e85GrUGtIxaflBX04SuzApZbvvFqXme8LNuKkyoMyoOmMW6npK8bTrNB/TSLG92hAcBLPuFQgadmyjXF0lKHuxDZjJhb1odaj9uJvnU2cgmRD4YRiBiXXW4AG76eeyR8bvB9lnVa+VDaX/JVAeAGu/nCqrYVoE828rmK70QhRwE8B8PupZDEdmwiIOWanzQJ0pkAdZ3DelwBNZ5LoxO/RYsng1oBtNfABjd6xh0OE/03Hn7FhFSpzhURIG3chGf1LFpchhgJqM3C922XXrwXNgxfWzIliD6MmMjrhaiBwIZpVQefzM7mozVMiA2ES/hg70hAHC3sm9+MpEg8yJFeOHM0okOH9aQCFJIZe386JEqU5IXqqEIpjB3DOzSc/n1tXkBAn1S/CV+sHZBEzugm63AqnMT3+Bwvw=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
